# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
author: viewtorino
title: vt-studio
description: viewtorino PodCast
email: admin@viewtorino.com
hashtag: viewtorino
keywords: britpop,recording,rock,dtm,software,gadget,music
url: https://viewtorino.studio
itunes_podcast: https://itunes.apple.com/jp/podcast/vt-studio/id1191487179
android_podcast: https://subscribeonandroid.com/viewtorino.studio/feed.xml

voices:
  ogata:
    name: ogata
    url: https://twitter.com/CuddlyDominion
  itoh:
    name: itoh
    url: https://twitter.com/itoh4126
  wkhr:
    name: wkhr
    url: https://twitter.com/wkhr2
  niwa:
    name: niwa
    url: https://twitter.com/ssniwa
  midori:
    name: midori
    url: https://twitter.com/midori_aiueo
  nakano:
    name: nakano
    url: https://twitter.com/nakanoise
  amax:
    name: amax
    url: https://twitter.com/amax_bass
  matsuda:
    name: まつだひかり
    url: https://twitter.com/niko9_niku9
  koichizikan:
    name: こいち
    url: https://twitter.com/koichizikan
  hasisisissy:
    name: hasisisissy
    url: https://twitter.com/hasisisissy
  path:
    name: イシカワ
    url: https://twitter.com/path021
  tsounds:
    name: コイデ
    url: https://twitter.com/tsoundsrepair
  mikanima:
    name: mikanima
    url: https://twitter.com/mikanima
  natsumi:
    name: 夏海
    url: https://twitter.com/milkan10_
  maeda:
    name: 前田佳祐
    url: https://twitter.com/kmcnmanm
  kyosuke:
    name: kyosuke
    url: https://twitter.com/kysknk
  shuntaro:
    name: shuntaro
    url: https://twitter.com/shuntakillsU
  szak:
    name: 松本文紀
    url: /
  idouk:
    name: 移動教室
    url: https://twitter.com/sukubaha
  kawamata:
    name: kawamata
    url: https://twitter.com/niger0mad
  satoh:
    name: satoh
    url: https://twitter.com/Free_Fall_Diver
  egawa:
    name: egawa
    url: https://twitter.com/sarapedals
  yoshimura:
    name: yoshimura
    url: https://twitter.com/yoshiroudou

# Build settings
language: ja
markdown: kramdown
sass:
  sass_dir: css
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
language: ja
markdown: kramdown
permalink: /ep/:title
sass:
  sass_dir: css
  style: compressed
timezone: Asia/Tokyo
